- name: Setup Debian 12 system
  hosts: all
  # we run this as local apply, as root, because sudo isn't even installed yet.
  #become: true

  vars:
    git_safe_directories:
      - /home/appuser/.oh-my-zsh
      - /home/appuser/FieldStation42

  tasks:
    - name: Ensure APT does not install recommends or suggests
      copy:
        dest: /etc/apt/apt.conf.d/99no-recommends
        content: |
          APT::Install-Recommends "false";
          APT::Install-Suggests "false";
        owner: root
        group: root
        mode: '0644'

    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Consider cache valid for 1 hour

    # Install packages
    - name: Install developer/admin packages
      apt:
        name:
          - aptitude
          - curl
          - git
          - screen
          - ruby
          - vim-nox
          - wget
          - zsh
          - bash
          - openssh-server  # This is the package for sshd on Debian
        state: present

    # weird git safe.directory hack for ansible OMZ
    - name: Ensure root Git config has only expected safe.directory entries
      copy:
        dest: /root/.gitconfig
        content: |
          [safe]
          {% for dir in git_safe_directories %}
          directory = {{ dir }}
          {% endfor %}
        owner: root
        group: root
        mode: '0644'
