---
- name: Install Opinionated XORG stack for FieldStation42
  hosts: all

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600 # Consider cache valid for 1 hour

    - name: Install lightdm, xfce, and apps
      ansible.builtin.apt:
        name:
          - lightdm
          - xorg
          - pulseaudio
          - pipewire
          #- pipewire-alsa
          - pipewire-audio
          - pipewire-pulse
          - wireplumber
          - rtkit # REQUIRED for pipewire / pulseaudio
          - easyeffects
          - conky-std
          - xfce4
          - xfce4-terminal
          - tilda
          - alsa-utils
          - pavucontrol
          - ffmpeg
          - mpv
          - xdotool
        state: present

    - name: Purge junk we don't want
      ansible.builtin.apt:
        name:
          - light-locker
        state: absent

    - name: Ensure autologin is set in lightdm.conf
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^autologin-user\\s*="
        line: "autologin-user = appuser"
        insertafter: "^\\[Seat:\\*\\]"

    - name: Copy desktop wallpaper
      ansible.builtin.copy:
        src: ../files/misc/2560px-SMPTE_Color_Bars.svg.png
        dest: "/home/appuser/2560px-SMPTE_Color_Bars.svg.png"

    - name: Copy conkyrc
      ansible.builtin.copy:
        src: ../files/misc/conkyrc
        dest: "/home/appuser/.conkyrc"

    - name: Copy conkyrc-right
      ansible.builtin.copy:
        src: ../files/misc/conkyrc-right
        dest: "/home/appuser/.conkyrc-right"
