- name: Clone FieldStation42 and prepare configuration
  hosts: all
  vars:
    app_user: appuser
    app_group: appuser
    app_home: /home/appuser
    app_shell: /bin/zsh

  tasks:
    - name: Ensure appuser home directory exists
      file:
        path: "{{ app_home }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        state: directory
        mode: '0755'

    - name: Clone FieldStation42 repo
      git:
        repo: https://github.com/shane-mason/FieldStation42
        dest: "{{ app_home }}/FieldStation42"
        version: main
        update: yes
        force: yes
      become: yes
      become_user: "{{ app_user }}"

    - name: Ensure conf directory exists
      file:
        path: "/home/{{ app_user }}/FieldStation42/conf"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'

    - name: Ensure catalog directory exists
      file:
        path: "/home/{{ app_user }}/FieldStation42/catalog"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'

    - name: Ensure runtime directory exists
      file:
        path: "/home/{{ app_user }}/FieldStation42/runtime"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
