- name: Install Python and misc deps for FieldStation42
  hosts: all

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Consider cache valid for 1 hour

    - name: Install Python and FieldStation42 deps
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
          - python3-tk
        state: present
