- name: Clone FieldStation42 and prepare configuration
  hosts: all
  vars:
    app_user: appuser
    app_group: appuser
    app_home: /home/appuser
    app_shell: /bin/zsh

  tasks:
    - name: Ensure appuser home directory exists
      file:
        path: "{{ app_home }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        state: directory
        mode: '0755'

    - name: Clone FieldStation42 repo
      git:
        repo: https://github.com/shane-mason/FieldStation42
        dest: "{{ app_home }}/FieldStation42"
        version: main
        update: yes
        force: yes
      become: yes
      become_user: "{{ app_user }}"

    - name: Ensure conf directory exists
      file:
        path: "/home/{{ app_user }}/FieldStation42/confs"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'

    - name: Ensure catalog directory exists
      file:
        path: "/home/{{ app_user }}/FieldStation42/catalog"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'

    - name: Ensure runtime directory exists
      file:
        path: "/home/{{ app_user }}/FieldStation42/runtime"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'

    - name: Touch runtime socket
      copy:
        dest: "/home/{{ app_user }}/FieldStation42/runtime/channel.socket"
        content: ""
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
        force: no  # Only creates if it doesn't exist

    - name: Copy channel config JSON files to FieldStation42/confs
      copy:
        src: "{{ item }}"
        dest: "/home/{{ app_user }}/FieldStation42/confs/{{ item | basename }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0644'
      loop: "{{ lookup('fileglob', '../channels/*.json', wantlist=True) }}"
